### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by carinaya** [UBC-MDS/mathdistops#59]
Hi guys! 
We did a very good job this week!
Since we do not publish our packages to pyPI, we specify how to install from poetry. 
So, next time after we finished publish, we need to modify the wording again to make it up-to-date.
I post here just to remind it will be one task for next week.

**Comment by sandygross** [comment]
Hi @carinaya,
thanks a lot for bringing that up! Lets keep that in mind for next week
