### ISSUE TITLE
Branch Organization

### ISSUE THREAD

**Issue by sandygross** [UBC-MDS/mathdistops#60]
Hi team, 

I would suggest that every time we merge small updates to the main, that we delete the branch after that, such that the repo looks cleaner and we do not have too much branches open; e.g. for this week I would suggest we only keep the branches related to the functions and their tests. What do u think?

**Comment by carinaya** [comment]
That sounds great! We can do that! It will be easier for us to track our project! Thanks @sandygross to bring it up!
