### ISSUE TITLE
Exponential distribution dataset discuss

### ISSUE THREAD

**Issue by czwcandy** [UBC-MDS/mathdistops#67]
For exponential distribution, I find one may fit with exponential. I just tried.  I provided the code and dataset here. You can try it to see it is fine to be used.
The dataset comes from R package named 'survival', named "lung". It is actually a survival analysis.
R code:
library(survival)
df= survival::lung
write.csv(df, file = "/Users/katherinechen/Desktop/lung_dataset.csv", row.names = FALSE)
Python:
file_path = "/Users/Katherinechen/Desktop/lung_dataset.csv"  
lung_df = pd.read_csv(file_path)
print(lung_df.head())
q = lung_df['time'].median()
cumulative_prob, plot = pexp(q, rate=0.1, graph=True)
print(cumulative_prob)
plot.display()

**Comment by carinaya** [comment]
That looks awesome! I will try it on the exponential usage example, thanks!
