### ISSUE TITLE
Codecov button

### ISSUE THREAD

**Issue by carinaya** [UBC-MDS/mathdistops#71]
When I was trying to create a pull request, I noticed someone have already link the codecov! That is awesome! Thanks!

How about we add the codecov button on the README file. It should be on the website of the codecov related to our repository, just one line url but so cool!

**Comment by sandygross** [comment]
Sounds good to me

**Comment by carinaya** [comment]
But who did the codecov job? cuz the link should be on the account of the codecov and only the person have access can have the button link.

**Comment by sandygross** [comment]
I think it was @sivakornchong, right?
